from . import admins
from . import auth
from . import attendance
from . import class_rooms
from . import dashboard
from . import exams
from . import marks
from . import students
from . import subjects
from . import teachers
from . import fees
from . import timetable
from . import assignments
from . import notifications