"""add profile image to users

Revision ID: 035e993a0bca
Revises: a1c14024431f
Create Date: 2026-02-14 01:00:32.976093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035e993a0bca'
down_revision: Union[str, Sequence[str], None] = 'a1c14024431f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('parents', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('students', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'profile_image')
    op.drop_column('students', 'profile_image')
    op.drop_column('parents', 'profile_image')
    op.drop_column('admins', 'profile_image')
    # ### end Alembic commands ###
