"""add_timetable_module

Revision ID: 302ce3cd1e8c
Revises: b57c05ffabb6
Create Date: 2026-02-01 01:52:51.587311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302ce3cd1e8c'
down_revision: Union[str, Sequence[str], None] = 'b57c05ffabb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
