"""Add created_at to Student and Teacher models

Revision ID: 458789f6e2e1
Revises: a15e2d9edbe5
Create Date: 2026-02-01 10:31:27.930580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458789f6e2e1'
down_revision: Union[str, Sequence[str], None] = 'a15e2d9edbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('teachers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'created_at')
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
